configs:
  - id: auto-tag-project
    type:
      settings:
        schema: builtin:tags.auto-tagging
        scope: environment
    config:
      name: project
      template: auto-tag-project.json

  - id: auto-tag-service
    type:
      settings:
        schema: builtin:tags.auto-tagging
        scope: environment
    config:
      name: service
      template: auto-tag-service.json

  - id: auto-tag-stage
    type:
      settings:
        schema: builtin:tags.auto-tagging
        scope: environment
    config:
      name: stage
      template: auto-tag-stage.json
